#!/bin/bash
# Generated by scripts/build.sh from src/; do not edit sb.sh directly.
# sb-generated-artifact: v1
# sb-module: 00-bootstrap
export LANG=en_US.UTF-8
umask 077

CORE_VERSION="1.10.7"
ACME_VERSION="3.1.4"
CORE_SHA256_AMD64="1951a0785c8b4e1e21e0640227a49528ca772aec3d680061652e3d6b687e00fe"
CORE_SHA256_ARM64="15b43a0a50b4e6962aca819d4f3055aaac75ca7481350d4aaebe93ed06b7af49"
CORE_SHA256_ARMV7="691882d609c877f97bc8d6f8645b97d12de81b6f7b89651df66489ef11b4c5d0"
ACME_ARCHIVE_SHA256="e5f8e187bbf5251e0cd8891f2622daab9850366bd17bea9f92c2fe2ee091fd32"
SOCKS_USERNAME="sb"
SB_DIR="/etc/sb"
SB_CONFIG="$SB_DIR/sb.json"
SB_BIN="$SB_DIR/sing-box"
SB_SERVICE="sb"
SYSTEMD_UNIT="/etc/systemd/system/${SB_SERVICE}.service"
OPENRC_UNIT="/etc/init.d/${SB_SERVICE}"
SHORTCUT="/usr/bin/sb"
SB_MANAGED_MARKER="$SB_DIR/.sb-managed"
ACME_HOME="$SB_DIR/acme"
ACME_BIN="$ACME_HOME/acme.sh"
ACME_CERT="$SB_DIR/acme-cert.pem"
ACME_KEY="$SB_DIR/acme-private.key"
ACME_IDENTITY="$SB_DIR/acme_server_name"
ACME_RELOAD="$SB_DIR/acme_reload.sh"
ACME_LOCK="$SB_DIR/acme.lock"
ACME_RELOAD_IDENTITY="# sb-acme-reload-v1"
ACME_CRON_MARKER="# sb-managed-acme"
RESTART_CRON_MARKER="# sb-managed-restart"
INSTALL_TRANSACTION_ACTIVE=0
ACME_STATE_BACKUP=
ACME_RESTORE_ACTIVE_ON_INTERRUPT=0
ACME_LOCK_FD=
ACME_LOCK_HELD=0
CERT_ACTIVATION_MAINTENANCE_OK=1

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;36m'
bblue='\033[0;34m'
plain='\033[0m'
red(){ echo -e "\033[31m\033[01m$1\033[0m";}
green(){ echo -e "\033[32m\033[01m$1\033[0m";}
yellow(){ echo -e "\033[33m\033[01m$1\033[0m";}
blue(){ echo -e "\033[36m\033[01m$1\033[0m";}
white(){ echo -e "\033[37m\033[01m$1\033[0m";}
readp(){
  if [[ -n ${2-} ]]; then
    IFS= read -r -p "$(yellow "$1")" "$2"
  else
    IFS= read -r -p "$(yellow "$1")"
  fi
}
if [[ $EUID -ne 0 ]]; then
  yellow "请以root模式运行脚本"
  exit 1
fi
stty erase $'\b' 2>/dev/null || stty erase '^H' 2>/dev/null

if [[ ! -f /etc/redhat-release ]] && ! grep -qE -i "alpine|debian|ubuntu|centos|red hat|redhat" /etc/issue /proc/version 2>/dev/null; then
  red "脚本不支持当前的系统，请选择使用Ubuntu、Debian、CentOS或Alpine系统。"
  exit 1
fi

op=$(cat /etc/redhat-release 2>/dev/null || cat /etc/os-release 2>/dev/null | grep -i pretty_name | cut -d \" -f2)
if [[ $(echo "$op" | grep -i -E "arch") ]]; then
  red "脚本不支持当前的 $op 系统，请选择使用Ubuntu、Debian、CentOS或Alpine系统。"
  exit 1
fi
case $(uname -m) in
armv7l) cpu=armv7;;
aarch64) cpu=arm64;;
x86_64) cpu=amd64;;
*) red "目前脚本不支持$(uname -m)架构"; exit 1;;
esac

hostname=$(hostname)
sb_version="v1.8.0"

valid_ipv4(){
  local ip=$1 IFS=. octets octet
  [[ $ip =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  read -r -a octets <<< "$ip"
  for octet in "${octets[@]}"; do
    ((10#$octet <= 255)) || return 1
  done
}

valid_ipv6(){
  local ip=$1 group nonempty=0
  local -a groups
  [[ -n $ip && ${#ip} -le 39 && $ip == *:* && $ip =~ ^[0-9A-Fa-f:]+$ ]] || return 1
  [[ $ip != ':' && $ip != '::' && $ip != '::1' && $ip != *:::* ]] || return 1
  [[ ! $ip =~ ^[Ff][Ee][89AaBb] && ! $ip =~ ^[Ff][CcDd] ]] || return 1
  if [[ $ip == *::* ]]; then
    [[ ${ip#*::} != *::* ]] || return 1
  fi
  IFS=':' read -r -a groups <<< "$ip"
  for group in "${groups[@]}"; do
    [[ -z $group ]] && continue
    [[ ${#group} -le 4 && $group =~ ^[0-9A-Fa-f]+$ ]] || return 1
    nonempty=$((nonempty + 1))
  done
  if [[ $ip == *::* ]]; then
    ((nonempty < 8))
  else
    ((nonempty == 8))
  fi
}

sanitize_location(){
  tr '\r\n\t' '   ' | sed 's/[[:cntrl:]]//g; s/[[:space:]][[:space:]]*/ /g; s/^ //; s/ $//' | cut -c1-160
}

v4v6_refresh(){
  local cache_file="$SB_DIR/.ip_cache" cache_tmp
  v4=$(curl --fail --silent --show-error -4 --max-time 5 https://myip.ipip.net 2>/dev/null | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -1)
  [[ -z $v4 ]] && v4=$(curl --fail --silent --show-error -4 --max-time 5 https://4.ipw.cn 2>/dev/null | tr -d '\r\n ')
  [[ -z $v4 ]] && v4=$(curl --fail --silent --show-error -4 --max-time 5 https://icanhazip.com 2>/dev/null | tr -d '\r\n ')
  valid_ipv4 "$v4" || v4=
  v6=$(curl --fail --silent --show-error -6 --max-time 5 https://icanhazip.com 2>/dev/null | tr -d '\r\n ')
  [[ -z $v6 ]] && v6=$(curl --fail --silent --show-error -6 --max-time 5 https://6.ipw.cn 2>/dev/null | tr -d '\r\n ')
  [[ -z $v6 ]] && v6=$(ip -6 addr show 2>/dev/null | grep 'inet6.*global' | awk '{print $2}' | cut -d/ -f1 | head -1)
  valid_ipv6 "$v6" || v6=
  v4dq=$(curl --fail --silent --show-error -4 --max-time 5 https://myip.ipip.net 2>/dev/null | sed 's/.*来自于：//; s/.*来自：//; s/.*Location: //' | sanitize_location)
  v6dq=$(curl --fail --silent --show-error -6 --max-time 5 https://ip.fm 2>/dev/null | sed 's/.*来自于：//; s/.*来自：//; s/.*Location: //' | sanitize_location)
  cache_tmp=$(mktemp "$SB_DIR/.ip_cache.XXXXXX") || return 1
  printf '%s\n%s\n%s\n%s\n' "$v4" "$v6" "$v4dq" "$v6dq" > "$cache_tmp"
  chmod 600 "$cache_tmp"
  mv -f "$cache_tmp" "$cache_file"
}

read_ip_cache(){
  local cache_file="$SB_DIR/.ip_cache"
  mapfile -t ip_cache < "$cache_file" 2>/dev/null || return 1
  v4=${ip_cache[0]-}
  v6=${ip_cache[1]-}
  v4dq=${ip_cache[2]-}
  v6dq=${ip_cache[3]-}
  valid_ipv4 "$v4" || v4=
  valid_ipv6 "$v6" || v6=
  [[ -n $v4 || -n $v6 ]]
}

v4v6(){
  local cache_file="$SB_DIR/.ip_cache"
  if [[ -f "$cache_file" ]]; then
    local cache_age=$(($(date +%s) - $(stat -c %Y "$cache_file" 2>/dev/null || echo 0)))
    if [[ $cache_age -lt 300 ]]; then
      read_ip_cache && return
    fi
  fi
  v4v6_refresh
}

# IP stack detection for domain_strategy
v6only(){
  if ip -4 addr show 2>/dev/null | grep -oP 'inet \K[0-9.]+' | grep -qv '^127\.'; then
    ipv=prefer_ipv4
  else
    ipv=prefer_ipv6
  fi
}

# Core download
inssb(){
  local sbcore="$CORE_VERSION" sbname temp_dir archive expected_sha256 actual_sha256 extracted_version
  red "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  green "安装固定版本 Sing-box v${sbcore}"
  sbname="sing-box-$sbcore-linux-$cpu"
  case "$cpu" in
    amd64) expected_sha256=$CORE_SHA256_AMD64 ;;
    arm64) expected_sha256=$CORE_SHA256_ARM64 ;;
    armv7) expected_sha256=$CORE_SHA256_ARMV7 ;;
    *) red "没有当前架构的 Sing-box 摘要"; return 1 ;;
  esac
  temp_dir=$(mktemp -d "$SB_DIR/.core.XXXXXX") || return 1
  archive="$temp_dir/$sbname.tar.gz"
  if ! curl --fail --location --proto '=https' --proto-redir '=https' --retry 2 \
    --connect-timeout 10 --max-time 180 -o "$archive" \
    "https://github.com/SagerNet/sing-box/releases/download/v$sbcore/$sbname.tar.gz"; then
    red "下载 Sing-box v${sbcore} 失败，请检查VPS是否可访问GitHub"
    rm -rf "$temp_dir"
    return 1
  fi
  actual_sha256=$(sha256sum "$archive" 2>/dev/null | awk '{print $1}')
  if [[ $actual_sha256 != "$expected_sha256" ]]; then
    red "Sing-box 压缩包 SHA-256 校验失败，拒绝安装"
    rm -rf "$temp_dir"
    return 1
  fi
  if ! tar -xzf "$archive" -C "$temp_dir" || [[ ! -x "$temp_dir/$sbname/sing-box" ]]; then
    red "Sing-box 压缩包不完整或解压失败"
    rm -rf "$temp_dir"
    return 1
  fi
  extracted_version=$("$temp_dir/$sbname/sing-box" version 2>/dev/null | awk '/version/{print $NF}')
  if [[ $extracted_version != "$CORE_VERSION" ]]; then
    red "内核版本校验失败：期望 $CORE_VERSION，实际 ${extracted_version:-未知}"
    rm -rf "$temp_dir"
    return 1
  fi
  if ! install -m 755 "$temp_dir/$sbname/sing-box" "$SB_BIN"; then
    red "安装 Sing-box 内核失败"
    rm -rf "$temp_dir"
    return 1
  fi
  rm -rf "$temp_dir"
  blue "成功安装 Sing-box 内核版本：$("$SB_BIN" version 2>/dev/null | awk '/version/{print $NF}')"
}
